force-app/main/default/objects/Pacient__c/Pacient__c.object-meta.xml
<CustomObject>
    <label>Pacient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Pacient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pacients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pacient__c/fields/Last_Visit__c.field-meta.xml
<CustomField>
    <fullName>Last_Visit__c</fullName>
    <label>Last Visit</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pacient__c/fields/Next_Visit__c.field-meta.xml
<CustomField>
    <fullName>Next_Visit__c</fullName>
    <label>Next Visit</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/profesionalTriggerTest.cls
@isTest
private with sharing class profesionalTriggerTest {

    @isTest
    static void updatePacient_lastVisitSetUp_nextVisitCorrectly(){
        //Given
        Pacient__c pacient1 = new Pacient__c();
        pacient1.Visit_frecuency__c = 'Every other week';
        pacient1.Last_Visit__c = System.today() -15;
        insert pacient1;

        //Then
        pacient1 = [SELECT Next_Visit__c, Last_Visit__c, Visit_frecuency__c FROM Pacient__c WHERE Id = :pacient1.Id];
        System.assertEquals(System.today(), pacient1.Next_Visit__c);
        pacient1.Last_Visit__c = System.today();

        // WHEN
        Test.startTest();
        update pacient1;
        Test.stopTest();

        //Then
        pacient1 = [SELECT Next_Visit__c, Last_Visit__c, Visit_frecuency__c FROM Pacient__c WHERE Id = :pacient1.Id];
        System.assertEquals(System.today() + 15, pacient1.Next_Visit__c);
    }

}