force-app/main/default/objects/Pacient__c/Pacient__c.object-meta.xml
<CustomObject>
    <label>Pacient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Pacient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pacients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pacient__c/fields/professional__c.field-meta.xml
<CustomField>
    <fullName>professional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>professional</label>
    <referenceTo>professional__c</referenceTo>
    <relationshipLabel>Pacients</relationshipLabel>
    <relationshipName>Pacients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/professional__c/professional__c.object-meta.xml
<CustomObject>
    <label>professional</label>
    <nameField>
        <label>professionals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>professionals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/professional__c/fields/schedules__c.field-meta.xml
<CustomField>
    <fullName>schedules__c</fullName>
    <label>Schedules</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Am</fullName>
                <default>true</default>
                <label>Am</label>
            </value>
            <value>
                <fullName>Pm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProfesionalService.cls
public with sharing class ProfesionalService {
    @AuraEnabled(cacheable=true)
    public static List<professional__c> getFilteredProfesionals(String searchText) {
        String likeValue = '%' + searchText + '%';
        return [
            SELECT Id, Name, Description__c, Image_URL__c, schedules__c
            FROM professional__c
            WHERE Name LIKE :likeValue
        ];
    }

    @AuraEnabled()
    public static void createProfesionalWithPacient(
        String profesionalName,
        String pacientName,
        String profesionalSchedule
        ){
        //Crear Profesional
        professional__c newProfessional = new professional__c();
        newProfessional.Name = profesionalName;
        newProfessional.Schedules__c = profesionalSchedule;
        insert newProfessional;

        //Crear paciente 
        Pacient__c newPacient = new Pacient__c();
        newPacient.Name = pacientName;
        insert newPacient;

    }
}